@startuml 123
start

if (У клиента есть аккаунт сервиса?) then (да)
    :Попросить ввести данные для авторизации пользователя;
    repeat
    if(Введенные данные коректны?) then (да)
        :Разрешить доступ к сервису;
    else(нет)
        :Указать,что данные не корректны;
        :Попросить авторизоваться заново;
    endif
    repeat while (Доступ был разрешен?) is (нет, повторить не более 3 раз)
  else (нет)
    :Попросить ввести данные для регистрации пользователя;
    repeat
    if(Введенные данные коректны?) then (да)
        :Разрешить доступ к сервису;
    else(нет)
        :Указать,что данные не корректны;
        :Попросить зарегистрироваться заново;
    endif
    repeat while (Доступ был разрешен?) is (нет, повторить не более 3 раз)
endif

if (Система повторила более 3 раз) then(да)
:Прервать операцию и попросить повторить позже;
stop
else(нет)
:Продолжить;
endif

:Система подтверждает учетные данные;

repeat
  :Клиент выбирает товар;
  if (Товар выбран?) then (да)
        :Добавить в корзину;
    else(нет)
        :Продолжить выбирать товар;
  endif
repeat while (Клиент выбрал все товары которые хотел?) is (нет);


:Переход к оформлению заказа;

if (Выбор способа получения заказа) then (Самовывоз)
        :Написать адрес магазина;
    else(Доставка)
        :Попросить ввести данные доставки;
endif

:Система проверяет наличие каждого товара в корзине;
repeat
if (Товар в наличии?) then (да)
        :Продолжить проверку;
    else(нет)
        :Уведомить об отсутвие товара клиента;
        if (Предложить выбрать альтернативный товар из аналагичной категории) then (да)
                :Удалить отсутвующий товар из корзины;
                :Клиент выбирает аналогичный товар и добавляет в корзину;
            else(нет)
                if (Предложить оставить заказ в ожидание поступления) then (да)
                    :Добавить заказ в ожидание поступления;
                    :Автоматически уведомить клиента о поступление товара;
                    stop
                else(нет)
                    :Удалить отсутвующий товар из корзины;
                    
                endif
        endif
endif
repeat while (Проверили все товары?) is (нет);

:Клиент нажимает кнопку оплатить;

fork


if (Система предлагает ввести промокод) then (Промокод есть)
        :Система проверяет актуальность промокода;

        if (Промокод действителен и корректен?) then (да)
             
            if (У промокода превышен лимит использования?) then (да)
                :Уведомить клиента о первышение использования промокода;
                else(нет)
                
                if (Промокод действует на выбранные товары?) then (да)
                    :Использовать промокод;
                    :Пересчитать стоимость с учетом скидки;
                else(нет)
                    :Уведомить клиента что промокод не действует на выбранные товары;
                endif 

            
            endif 

            
            else(нет)
            :Уведомить клиента о недействительности промокода;
        endif 

    else(Промокода нету)
        :Система переходит сразу к оплате;
endif




:Предложить клиенту выбрать способ оплаты Кредитная карта/PayPal/Банковский перевод/QR;

if (Клиент выбирает) then (Кредитная карта/PayPal)
        :Попросить ввести данные для оплаты;
    else(Банковский перевод/QR)
        :Прислать данные для оплаты;
endif    

repeat
if (Система проверяет платежные детали на корректный ввод) then (да)
        :Производит транзакцию;
        :Система разрешает дальнейший доступ;
    else(нет)
        :Просит проверить или изменить способ оплаты;
        :Предложить клиенту связаться со службой поддержки в случае наличия вопросов;
endif
repeat while (Доступ был разрешен?) is (нет, повторить не более 3 раз) 

if (Система повторила более 3 раз) then(да)
:Прервать операцию и попросить повторить позже;
stop
else(нет)
:Продолжить;
endif

if (Транзакция прошла?) then (да)
        :Система завершает оплату ;
    else(нет)
        
        if (Проверить причину отказа) then (недостаточно средств у клиента)
            :Уведомить клиента о недостаточности средств;
            :Предложить альтернативный способ оплаты;
            repeat
            if (Транзакция прошла?) then (да)
                :Система завершает оплату ;
                else(нет)
                :Попросить клиента пополнить счет;
                :Предложить клиенту связаться со службой поддержки в случае наличия вопросов;
                
            endif
            repeat while (Оплата прошла?) is (нет,повторить не более 2 раз)

            if (Система повторила более 2 раз) then(да)
            :Прервать операцию и попросить повторить позже;
            stop
            else(нет)
            :Продолжить;
            endif

            else(платежная система недоступна)
                :Сообщить клиенту о неисправности системы;
                :Попросить оплатить корзину покупок позже;
                :Предложить клиенту связаться со службой поддержки в случае наличия вопросов;
                :Вернуть средства при списание;
                :Автоматически сообщить дежурному разработчику о проблеме;
                :Записать ошибку;
                stop
        endif
endif



fork again
  :Система передает корзину клиента сотруднику склада;
  :Сотрудник собирает корзину клиента;
  :Сотрудник сверяется со списком;
  :Сотрудник отмечает в система готовность заказа;
  if (Какой способ получения выбрал клиент?) then (Самовывоз)
        :Сотрудник передает заказ в зону получения;
    else(Доставка)
        :Сотрудник передает заказ в доставку;
endif  
end fork

:Генерируется счет-фактура;
:Система уведомляет клиента о готовности заказа и сроках получения;

if (Способ получения) then (Самовывоз)
        :Клиент забирает заказ;
    else(Доставка)
        :Заказ переходит в статус Отправлен;
        :Ситема обновляет статус по мере продвижения доставки;
        :Клиент получает уведомления о каждом изменении статуса;
endif 
:Клиент получил заказ;

@enduml