@startuml class_activity
start
:Был ли клиент корректен?;
if (Корректен?) then (да)
  :Сохранить клиента в базе данных;
  :Отправить уведомительный email;
else (нет)
  :Выдать ошибку блокировки;
endif
stop
@enduml