@startuml step2
skinparam databaseBackgroundColor #yellow


actor Customer
participant WebUI
participant OrderController
participant PaymentService
database Database 
participant NotificationService


group "Оформление заказа" 
    Customer -> WebUI: InitiateOrder(orderDetails)
    activate Customer
    WebUI -> OrderController: processOrder(orderDetails)
    activate WebUI
    activate OrderController
    OrderController -> Database: saveOrder(orderDetails)
    activate Database 
    Database --[#green]> OrderController: orderSaved 
    deactivate Database

end

group "Оплата" 

  OrderController -> PaymentService: processPayment(paymentinfo)
  activate PaymentService
  alt successful payment
    PaymentService --[#green]> OrderController : paymentSuccess(paymentConfirmation)
    PaymentService --[#LightBlue]> NotificationService : sendOrderNotification(orderId)
  else payment failed
    PaymentService --[#red]> OrderController: paymentFailure(errorMessage)
    deactivate PaymentService 
  end

end

group "Подтверждение" 
  OrderController --> WebUI: orderConfirmation(confirmationDetails)
  deactivate OrderController
  WebUI --> Customer: displayConfirmation(confirmationDetails)
  deactivate WebUI
  deactivate Customer
end

@enduml
